apiVersion: v1
data:
  DB_URL: ''
  AWS_ID: ''
  AWS_KEY: ''
  REGION: ''
  SENTINEL_1: ''
  SENTINEL_2: ''
  SENTINEL_3: ''
  SENTINEL_PASS: ''
kind: Secret
metadata:
  name: env-secret
  namespace: openfaas-fn
type: Opaque
